name: Runs All Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: run tests
        run: npm run test:unit

  preview:
    runs-on: ubuntu-latest
    needs:
      - test
    environment:
      name: preview
      url: ${{ steps.vercel-preview.outputs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Vercel
        id: vercel-preview
        run: VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID}} VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID}} npx vercel --scope nac-in-ua --token=${{ secrets.VERCEL_TOKEN }}

  # build:
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Cache Dependencies
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: ${{ runner.os }}-node-

  #     - name: Setup Node 16
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'

  #     - name: Install Dependencies
  #       run: npm ci

  #     - name: Build
  #       run: npm run build

  #     - name: upload build artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: build
  #         path: dist
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   environment:
  #     name: preview
  #     url: ${{ steps.deploy-vercel-preview.outputs.preview-url }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Download repository
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: build

  #     - name: Deploy to Preview
  #       id: deploy-vercel-preview
  #       uses: amondnet/vercel-action@v20
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         vercel-args: '--prod'
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
  #         working-directory: ./
